project_id = "ivmuypzlemoxdctkwhqw"

[functions.classify-restaurant-cuisine]
verify_jwt = false

[functions.batch-classify-restaurants]
verify_jwt = false

[functions.import-restaurants]
verify_jwt = false

[functions.monthly-review-reminder]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = true

[functions.verify-restaurant-claim]
verify_jwt = true

[functions.create-new-restaurant]
verify_jwt = true